//
// HotelBack0View.m
// Generated by Core Animator version 1.3.2 on 1/6/17.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import "HotelBack0View.h"

@interface HotelBack0PassthroughView : UIView
@end
@implementation HotelBack0PassthroughView
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event {
    for ( UIView *subview in self.subviews ) {
        if ( [subview pointInside:[self convertPoint:point toView:subview] withEvent:event]) { return true; }
    }
    return false;
}
@end

@implementation HotelBack0View

#pragma mark - Life Cycle

- (instancetype)init
{
	return [self initWithFrame:CGRectMake(0,0,496,748)];
}

- (instancetype)initWithFrame:(CGRect)frame
{
	self = [super initWithFrame:frame];
	if (self)
	{
		[self setupHierarchy];
	}
	return self;
}

- (instancetype)initWithCoder:(NSCoder *)coder
{
	self = [super initWithCoder:coder];
	if (self)
	{
		[self setupHierarchy];
	}
	return self;
}

#pragma mark - Scaling

- (void)layoutSubviews
{
	[super layoutSubviews];

	UIView *scalingView = self.viewsByName[@"__scaling__"];
	float xScale = self.bounds.size.width / scalingView.bounds.size.width;
	float yScale = self.bounds.size.height / scalingView.bounds.size.height;
	switch (self.contentMode) {
		case UIViewContentModeScaleToFill:
			break;
		case UIViewContentModeScaleAspectFill:
		{
			float scale = MAX(xScale, yScale);
			xScale = scale;
			yScale = scale;
			break;
		}
		default:
		{
			float scale = MIN(xScale, yScale);
			xScale = scale;
			yScale = scale;
			break;
		}
	}
	scalingView.transform = CGAffineTransformMakeScale(xScale, yScale);
	scalingView.center = CGPointMake(CGRectGetMidX(self.bounds), CGRectGetMidY(self.bounds));
}

#pragma mark - Setup

- (void)setupHierarchy
{
	NSMutableDictionary *viewsByName = [NSMutableDictionary dictionary];
	NSBundle *bundle = [NSBundle bundleForClass:[self class]];

	UIView *__scaling__ = [UIView new];
	__scaling__.bounds = CGRectMake(0, 0, 496, 748);
	__scaling__.center = CGPointMake(248.3, 374.4);
	[self addSubview:__scaling__];
	viewsByName[@"__scaling__"] = __scaling__;

	HotelBack0PassthroughView *galerryGrandHotelElMiradorIntroductionHotelsImage3__root = [HotelBack0PassthroughView new];
	HotelBack0PassthroughView *galerryGrandHotelElMiradorIntroductionHotelsImage3__xScale = [HotelBack0PassthroughView new];
	HotelBack0PassthroughView *galerryGrandHotelElMiradorIntroductionHotelsImage3__yScale = [HotelBack0PassthroughView new];
	UIImageView *galerryGrandHotelElMiradorIntroductionHotelsImage3 = [UIImageView new];
	UIImage *imgGalerryGrandHotelElMiradorIntroductionHotelsImage3 = [UIImage imageNamed:@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3.jpg" inBundle:bundle compatibleWithTraitCollection:nil];
	if ( imgGalerryGrandHotelElMiradorIntroductionHotelsImage3 == nil ) { NSLog(@"** Warning: Could not create image from 'galerry_grand-hotel-el-mirador-introduction-hotels-image-3.jpg'."); }
	galerryGrandHotelElMiradorIntroductionHotelsImage3.image = imgGalerryGrandHotelElMiradorIntroductionHotelsImage3;
	galerryGrandHotelElMiradorIntroductionHotelsImage3.contentMode = UIViewContentModeCenter;
	galerryGrandHotelElMiradorIntroductionHotelsImage3.bounds = CGRectMake(0, 0, 826.0, 388.0);
	galerryGrandHotelElMiradorIntroductionHotelsImage3__root.layer.position = CGPointMake(-297.903, 373.248);
	galerryGrandHotelElMiradorIntroductionHotelsImage3__xScale.transform = CGAffineTransformMakeScale(1.92, 1.00);
	galerryGrandHotelElMiradorIntroductionHotelsImage3__yScale.transform = CGAffineTransformMakeScale(1.00, 1.92);
	galerryGrandHotelElMiradorIntroductionHotelsImage3__root.transform = CGAffineTransformMakeRotation(0.000);
	[__scaling__ addSubview:galerryGrandHotelElMiradorIntroductionHotelsImage3__root];
	[galerryGrandHotelElMiradorIntroductionHotelsImage3__root addSubview:galerryGrandHotelElMiradorIntroductionHotelsImage3__xScale];
	[galerryGrandHotelElMiradorIntroductionHotelsImage3__xScale addSubview:galerryGrandHotelElMiradorIntroductionHotelsImage3__yScale];
	[galerryGrandHotelElMiradorIntroductionHotelsImage3__yScale addSubview:galerryGrandHotelElMiradorIntroductionHotelsImage3];
	[__scaling__ addSubview:galerryGrandHotelElMiradorIntroductionHotelsImage3__root];
	viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__root"] = galerryGrandHotelElMiradorIntroductionHotelsImage3__root;
	viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__xScale"] = galerryGrandHotelElMiradorIntroductionHotelsImage3__xScale;
	viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__yScale"] = galerryGrandHotelElMiradorIntroductionHotelsImage3__yScale;
	viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3"] = galerryGrandHotelElMiradorIntroductionHotelsImage3;

	self.viewsByName = viewsByName;
}

#pragma mark - HotelBackGround

- (void)addHotelBackGroundAnimation
{
	[self addHotelBackGroundAnimationWithBeginTime:0 andFillMode:kCAFillModeBoth andRemoveOnCompletion:NO];
}

- (void)addHotelBackGroundAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion
{
	[self addHotelBackGroundAnimationWithBeginTime:0 andFillMode:removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth andRemoveOnCompletion:removedOnCompletion];
}

- (void)addHotelBackGroundAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion
{
	CAMediaTimingFunction *linearTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
	CAMediaTimingFunction *easeInOutTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut];
	CAMediaTimingFunction *easeOutTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];

	CAKeyframeAnimation *galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.duration = 9.000;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.values = @[@(1.924), @(1.924), @(2.364), @(1.920)];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.keyTimes = @[@(0.000), @(0.101), @(0.667), @(1.000)];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.timingFunctions = @[linearTiming, easeInOutTiming, easeInOutTiming];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.repeatCount = HUGE_VALF;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.beginTime = beginTime;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.fillMode = fillMode;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__xScale"] layer] addAnimation:galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleXAnimation forKey:@"HotelBackGround_ScaleX"];

	CAKeyframeAnimation *galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.duration = 9.000;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.values = @[@(1.924), @(1.924), @(2.364), @(1.920)];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.keyTimes = @[@(0.000), @(0.101), @(0.667), @(1.000)];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.timingFunctions = @[linearTiming, easeInOutTiming, easeInOutTiming];
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.repeatCount = HUGE_VALF;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.beginTime = beginTime;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.fillMode = fillMode;
	galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__yScale"] layer] addAnimation:galerryGrandHotelElMiradorIntroductionHotelsImage3ScaleYAnimation forKey:@"HotelBackGround_ScaleY"];

	CAKeyframeAnimation *galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.duration = 10.000;
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.values = @[@(0.797), @(648.705), @(1096.266), @(2.859)];
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.keyTimes = @[@(0.000), @(0.200), @(0.700), @(1.000)];
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.timingFunctions = @[easeInOutTiming, easeInOutTiming, easeOutTiming];
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.repeatCount = HUGE_VALF;
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.beginTime = beginTime;
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.fillMode = fillMode;
	galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__root"] layer] addAnimation:galerryGrandHotelElMiradorIntroductionHotelsImage3TranslationXAnimation forKey:@"HotelBackGround_TranslationX"];
}

- (void)removeHotelBackGroundAnimation
{
	[[self.viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__xScale"] layer] removeAnimationForKey:@"HotelBackGround_ScaleX"];
	[[self.viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__yScale"] layer] removeAnimationForKey:@"HotelBackGround_ScaleY"];
	[[self.viewsByName[@"galerry_grand-hotel-el-mirador-introduction-hotels-image-3__root"] layer] removeAnimationForKey:@"HotelBackGround_TranslationX"];
}

- (void)removeAllAnimations
{
	for (UIView *view in self.viewsByName.allValues)
	{
		[view.layer removeAllAnimations];
	}
}

@end