//
// SplashTitleAnimationView.h
// Generated by Core Animator version 1.3.2 on 12/30/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

@import UIKit;

IB_DESIGNABLE
@interface SplashTitleAnimationView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// Untitled Animation
- (void)addUntitledAnimation;
- (void)addUntitledAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addUntitledAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addUntitledAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addUntitledAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeUntitledAnimation;

- (void)removeAllAnimations;

@end